const cryptoicons = {
  BTC: require("./color/btc.png"),
  ETH: require("./color/eth.png"),
  BNB: require("./color/bnb.png"),
  XRP: require("./color/xrp.png"),
  ADA: require("./color/ada.png"),
  DOGE: require("./color/doge.png"),
  MATIC: require("./color/matic.png"),
  SOL: require("./color/sol.png"),
  DOT: require("./color/dot.png"),
  LTC: require("./color/ltc.png"),
  AVAX: require("./color/avax.png"),
  SHIB: require("./color/shibxm.png"),
  TRX: require("./color/trx.png"),
  LINK: require("./color/link.png"),
  UNI: require("./color/uni.png"),
  ATOM: require("./color/atom.png"),
  ETC: require("./color/etc.png"),
  XLM: require("./color/xlm.png"),
  FIL: require("./color/fil.png"),
  BCH: require("./color/bch.png"),
  ARB: require("./color/arb.png"),
  HBAR: require("./color/hbar.png"),
  CRO: require("./color/CRO.png"),
  APE: require("./color/ape.png"),
  ALGO: require("./color/algo.png"),
  GRT: require("./color/grt.png"),
  FTM: require("./color/ftm.png"),
  QNT: require("./color/qnt.png"),
  EOS: require("./color/eos.png"),
  MANA: require("./color/mana.png"),
  THETA: require("./color/theta.png"),
  AAVE: require("./color/aave.png"),
  AXS: require("./color/axs.png"),
  XTZ: require("./color/xtz.png"),
  SAND: require("./color/sand.png"),
  IMX: require("./color/imx.png"),
  CHZ: require("./color/chz.png"),
  NEO: require("./color/neo.png"),
  CRV: require("./color/crv.png"),
  MKR: require("./color/mkr.png"),
  SNX: require("./color/snx.png"),
  LUNC: require("./color/lunc.png"),
  ZEC: require("./color/zec.png"),
  FTT: require("./color/ftt.png"),
  DASH: require("./color/dash.png"),
  MIOTA: require("./color/miota.png"),
  LRC: require("./color/lrc.png"),
  FLR: require("./color/flr.png"),
  DYDX: require("./color/dydx.png"),
  "1INCH": require("./color/1inch.png"),
  ENJ: require("./color/enj.png"),
  BAT: require("./color/bat.png"),
  ANKR: require("./color/ankr.png"),
  BAL: require("./color/bal.png"),
  FET: require("./color/fet.png"),
  GALA: require("./color/gala.png"),
  COMP: require("./color/comp.png"),
  YFI: require("./color/yfi.png"),
  ENS: require("./color/ens.png"),
  LUNA2: require("./color/luna2.png"),
  SUSHI: require("./color/sushi.png"),
  ZRX: require("./color/zrx.png"),
  BAND: require("./color/band.png"),
  BICO: require("./color/bico.png"),
  CTSI: require("./color/ctsi.png"),
  SKL: require("./color/skl.png"),
  LPT: require("./color/lpt.png"),
  AMP: require("./color/amp.png"),
  STORJ: require("./color/storj.png"),
  UMA: require("./color/uma.png"),
  API3: require("./color/api3.png"),
  KNC: require("./color/knc.png"),
  REN: require("./color/ren.png"),
  ALICE: require("./color/alice.png"),
  OXT: require("./color/oxt.png"),
  BNT: require("./color/bnt.png"),
  OGN: require("./color/ogn.png"),
  SRM: require("./color/srm.png"),
  //   ENG: require("./color/eng.png"),
  //   CELO: require("./color/celo.png"),
  //   SGB: require("./color/sgb.png"),
  //   USDC: require("./color/usdc.png"),
  //   USDT: require("./color/usdt.png"),
};
export default cryptoicons;
